/**
 * Caploom Changelog — single source of truth for versioning.
 *
 * HOW TO UPDATE:
 *   1. Add a new entry at the TOP of the `CHANGELOG` array
 *   2. Bump the version number following semver:
 *      - major: platform architecture redesign (1.x → 2.x)
 *      - minor: new feature (+0.1.0)
 *      - patch: bug fix / tweak (+0.0.1)
 *   3. The frontend reads CHANGELOG[0] to display the current version
 */

export type ChangelogEntry = {
  version: string;          // "1.4.0"
  date: string;             // "2026-04-24"
  type: "major" | "minor" | "patch";
  title: string;            // short headline
  description: string;      // 1-2 sentence summary
};

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: "2.32.0",
    date: "2026-05-06",
    type: "minor",
    title: "DCF Professional Upgrade — WACC via CAPM, Dual TV, Sensitivity Table",
    description: "新增 WACC 計算引擎 (CAPM: Rf + β×ERP)、終端價值雙方法 (Gordon Growth + Exit Multiple)、年中折現慣例、EV→Equity 橋接明細（含少數股權/特別股）、5×5 敏感度分析熱力圖。DCF Tab UI 全面升級。i18n EN + zh-TW 完整支援。",
  },
  {
    version: "2.31.3",
    date: "2026-05-06",
    type: "patch",
    title: "QA Round 4 — Medium & Low severity fixes",
    description: "Medium: AllocationDialog placeholders i18n 化、ESign 表單重設時序修正、CompanySettings useEffect 依賴修正、ESign/RoundDetail icon-only 按鈕加 aria-label、DB list query 加 LIMIT、delete 函數加 cascade risk 註解。Low: EstimatedValuation 移至 components/、刪除 ComponentShowcase 孤立檔、移除 console.log 殘留。",
  },
  {
    version: "2.31.2",
    date: "2026-05-06",
    type: "patch",
    title: "QA Round 4 — High severity fixes",
    description: "Nav: split single Legal item into Privacy + Terms (sidebar + mobile). Backend: allocation advance race condition fix with post-update verification for all state transitions. Audit: platform template operations now log companyId: 0. i18n: replaced hardcoded English toast messages in ESign (4), CompanySettings (1), Team (3) with react-i18next EN/zh-TW translations.",
  },
  {
    version: "2.31.1",
    date: "2026-05-06",
    type: "patch",
    title: "Security — QA Round 4 critical fixes",
    description: "Fixed cross-tenant signing template access (getTemplate now filters by companyId). Strengthened allocation create form validation and double-submit prevention. Hardened transfer ownership confirmation guard.",
  },
  {
    version: "2.31.0",
    date: "2026-05-05",
    type: "minor",
    title: "Allocation — Skip Term Sheet option",
    description: "Added 'Skip (no term sheet)' checkbox to the allocation edit dialog. When checked, the term sheet URL requirement is bypassed for advancing to Committed. Agreement URL remains mandatory.",
  },
  {
    version: "2.30.3",
    date: "2026-05-05",
    type: "patch",
    title: "Allocation — Move Advance into Edit dialog",
    description: "Removed the standalone Advance button from the allocation table. Advance is now only available inside the Edit dialog, where required fields (term sheet URL, etc.) can be filled first. Advance auto-saves the form before advancing.",
  },
  {
    version: "2.30.2",
    date: "2026-05-05",
    type: "patch",
    title: "Team — Delete invitation records",
    description: "Admins can now permanently delete any invitation record (pending, revoked, accepted, or expired) from the Team management page.",
  },
  {
    version: "2.30.1",
    date: "2026-05-05",
    type: "patch",
    title: "修復團隊邀請 — 登入後自動回到 Join 頁完成 accept",
    description: "修正邀請連結登入後導向首頁、未回到 /join?token= 導致 acceptInvitation 未觸發的問題。改用 Clerk openSignIn 搭配 afterSignInUrl 確保登入後回到 Join 頁自動完成接受流程。",
  },
  {
    version: "2.30.0",
    date: "2026-05-05",
    type: "minor",
    title: "Dashboard 重新排版 — 三區制 + Fundraising Goal",
    description: "Dashboard 全面重新排版：Zone 1 KPI 卡片不變，Zone 2 Ownership Pie + Fundraising Summary（累計募資、最新估值、已結束輪次、投資人數），Zone 3 獨立 Fundraising Goal（進度條 + 狀態分佈 + 底部統計），Zone 4 簡化 All Rounds 表格。移除舊的 Valuation Bar Chart、Recent Allocations、RoundProgress 元件。",
  },
  {
    version: "2.29.0",
    date: "2026-05-05",
    type: "minor",
    title: "Dashboard 修正：表格對齊 + Pipeline 只顯示進行中 Round",
    description: "修正 Recent Activity allocation 表格 shares/amount 欄位標題與內容未對齊（CSS specificity 問題）。Pipeline Round Progress 改為只顯示未結束的 round，已 closed 的不再出現。新增 rebuild-allocations-from-register.ts 腳本從 Share Register 反推建立正確的 allocations。",
  },
  {
    version: "2.28.1",
    date: "2026-05-05",
    type: "patch",
    title: "移除 auto-seed 自動觸發，修正股東分配錯亂",
    description: "移除 router 中三處自動觸發（fundingRounds.list、allocations.list、register.list），防止頁面載入時隨機輪轉分配投資人到錯誤的 funding round。新增 cleanup-auto-seeded.ts 腳本清理被錯誤建立的 allocations、register entries 和 snapshots。",
  },
  {
    version: "2.28.0",
    date: "2026-05-05",
    type: "minor",
    title: "NTD/USD 幣別切換 + Register 自動同步",
    description: "RoundDetail、Home、ShareRegister 三個頁面的 Allocation 表格全面支援 NTD/USD 幣別切換。新增 Register 自動同步機制：載入 Share Register 頁面時自動檢測 issued allocation 並補建缺少的 register entry + snapshot，不再需要手動執行腳本。",
  },
  {
    version: "2.27.0",
    date: "2026-05-04",
    type: "minor",
    title: "RoundDetail i18n 修復 + Demo Allocation 金額調整腳本",
    description: "修復 RoundDetail 頁面 10 個缺漏的 i18n 翻譯鍵（EN/zh-TW），移除所有 fallback 硬編碼。新增 adjust-demo-allocations.ts 腳本，將 A Round 8 位投資人總額從 NT$1 億調整為 NT$6 千萬，保留 NT$4 千萬未認領。",
  },
  {
    version: "2.26.0",
    date: "2026-05-04",
    type: "minor",
    title: "首頁 Allocations 表格 + 募資輪進度卡片",
    description: "Allocations 表格獨立全寬顯示最近 6 筆分配明細。原 Allocation Funnel 的狀態摘要合併至新「募資輪進度」卡片頂部，下方依輪次顯示堆疊進度條、完成百分比與狀態圖例。",
  },
  {
    version: "2.25.0",
    date: "2026-05-04",
    type: "minor",
    title: "股東名冊日期排序",
    description: "股東名冊的篩選條件從「按投資人名稱」改為「日期排序」下拉選單，可選擇由新到舊或由舊到新排列，更符合實際使用需求。",
  },
  {
    version: "2.24.2",
    date: "2026-05-04",
    type: "patch",
    title: "Analysis i18n 完整化 + beta 標籤",
    description: "Projections、Waterfall、AntiDilution 三頁面所有 hardcoded 英文字串替換為 i18n 翻譯鍵（共 35+ 鍵）。Analysis 側邊欄群組加上 beta 下標。",
  },
  {
    version: "2.24.1",
    date: "2026-05-04",
    type: "patch",
    title: "Investor Portal — Contact Platform Admin + i18n",
    description: "Investor Portal 無存取權時改為聯絡平台管理員（mailto），不再顯示聯絡公司管理員。同時將頁面所有硬編碼英文字串 i18n 化（中英雙語）。",
  },
  {
    version: "2.24.0",
    date: "2026-05-04",
    type: "minor",
    title: "Admin: Delete Company (with confirmation)",
    description: "平台管理員可在後台永久刪除公司，需輸入完整公司名稱確認。刪除範圍涵蓋所有業務資料、團隊成員、加密金鑰與公司記錄本身。操作記錄於管理員稽核日誌。",
  },
  {
    version: "2.23.1",
    date: "2026-05-04",
    type: "patch",
    title: "Paid Plan Upgrade — Contact Admin Flow",
    description: "標準版與進階版升級按鈕改為 mailto 聯繫管理員，FeatureGate 升級按鈕同步改為寄信流程，企業版與頁尾「聯繫我們」也統一導向管理員信箱。",
  },
  {
    version: "2.23.0",
    date: "2026-05-04",
    type: "minor",
    title: "Security & Data Consistency Hardening",
    description: "移除 Team.tsx 全部 dangerouslySetInnerHTML 防止 XSS，改用安全的 React 元素插值；allocation advance 加入樂觀鎖防止並發雙重 issue；waterfall 計算 NaN 防護（liquidationMultiple null guard）。",
  },
  {
    version: "2.22.2",
    date: "2026-05-04",
    type: "patch",
    title: "QA Round 2 Fixes",
    description: "修正 Home.tsx setState-during-render（改用 useEffect）、Rounds 表單新增財務欄位驗證、ShareRegister toast 錯誤訊息加上前綴、Esop.tsx 6 處 title 屬性 i18n 化、ShareRegister 殘留英文全部替換為 t() 呼叫。",
  },
  {
    version: "2.22.1",
    date: "2026-05-04",
    type: "patch",
    title: "QA Fixes — Low Priority",
    description: "移除孤立檔案、NotFound 加 DashboardLayout、ESOP exercise/settle cache invalidation 修正、Export 按鈕 loading 閃現修復、Onboarding skip 持久化至 localStorage。",
  },
  {
    version: "2.22.0",
    date: "2026-05-04",
    type: "minor",
    title: "QA Fixes — Medium Priority",
    description: "表格手機端橫向捲動、OnboardingWizard 防閃爍 + 逾時處理、表單按鈕 pending 狀態、後端錯誤格式化、v1 頁面硬編碼字串全面 i18n 化。",
  },
  {
    version: "2.21.1",
    date: "2026-05-04",
    type: "patch",
    title: "QA Fixes — Critical & High Priority",
    description: "RoleGuard 安全性修補（阻擋無公司使用者直接進入頁面）、所有主要頁面加入 Error State、Admin 範本路由改用 adminProcedure、補齊遺漏 i18n 翻譯鍵。",
  },
  {
    version: "2.21.0",
    date: "2026-04-30",
    type: "minor",
    title: "Onboarding Wizard — 新使用者引導流程",
    description: "全新註冊使用者首次登入時，自動顯示引導精靈。透過簡潔的 2 步驟流程（公司名稱 + 英文名 + 統編 → 完成），快速建立公司並進入儀表板。支援中英雙語。",
  },
  {
    version: "2.20.1",
    date: "2026-04-30",
    type: "patch",
    title: "手機版改善 — 登出按鈕 + 更多選單完善",
    description: "手機版 header 新增登出按鈕。「更多」選單加入使用者資訊區塊（頭像 + 名稱 + 登出）、Compliance & Tax 完整導航、訂閱與說明入口。修正 Investors 頁面 15 個缺漏 i18n key。修正桌面版 signOut 翻譯 key 路徑。",
  },
  {
    version: "2.20.0",
    date: "2026-04-30",
    type: "minor",
    title: "平台範本管理 — Admin 後台統一管理電子簽名範本",
    description: "Admin Panel 新增 Templates 頁面。平台管理員可上傳、編輯、刪除合約範本，並依文件類型分類、設定最低方案門檻。公司端依訂閱方案即時可見對應範本，無需手動推送。",
  },
  {
    version: "2.19.0",
    date: "2026-04-30",
    type: "minor",
    title: "RSU（限制性股票單位）— Plus/Enterprise",
    description: "ESOP 頁面新增 Options/RSU 分頁切換。RSU 完整生命週期：Grant → Vest → 自動交割普通股至股東名冊。歸屬交割時自動計算台灣應稅所得（FMV × 交割股數）。功能僅限 Plus/Enterprise 方案。",
  },
  {
    version: "2.18.0",
    date: "2026-04-29",
    type: "minor",
    title: "Security Phase 5 — 金鑰輪替與稽核",
    description: "Super Admin 可於安全頁面一鍵輪替平台 DEK，所有輪替操作自動記錄至 admin audit log。安全架構五階段全數完成。",
  },
  {
    version: "2.17.0",
    date: "2026-04-29",
    type: "minor",
    title: "Security Phase 4 — DocuSeal API Key / Webhook Secret 加密",
    description: "DocuSeal API 金鑰與 webhook secret 加入 AES-256-GCM 加密雙寫，讀取時優先解密 _enc 欄位。",
  },
  {
    version: "2.16.0",
    date: "2026-04-29",
    type: "minor",
    title: "Security Phase 3 — 核心交易金額加密（AES-256-GCM 雙寫）",
    description: "allocations / shareRegisterEntries / instruments / shareTransfers 四張核心交易表的金額與股數欄位加入 AES-256-GCM 加密雙寫，共 22 個財務欄位。",
  },
  {
    version: "2.15.0",
    date: "2026-04-29",
    type: "minor",
    title: "Security Phase 2 — PII 欄位級加密（AES-256-GCM 雙寫模式）",
    description: "users / companies / shareholders / investors 四張表的 PII 欄位加入 AES-256-GCM 加密雙寫。新增 platform DEK、blind index（HMAC-SHA256）供加密後 email 查詢。",
  },
  {
    version: "2.14.0",
    date: "2026-04-29",
    type: "minor",
    title: "Admin RBAC 精簡為 2 角色（super_admin / admin）",
    description: "移除 support 與 viewer 兩個管理員角色，僅保留 super_admin 和 admin。精簡 DB enum、權限矩陣、團隊管理 UI 與 i18n 翻譯。",
  },
  {
    version: "2.13.0",
    date: "2026-04-29",
    type: "minor",
    title: "Admin RBAC 權限系統 — 4 角色 + 團隊管理頁面",
    description: "新增平台管理員 4 角色 RBAC（super_admin/admin/support/viewer），每角色有獨立的 sidebar 可視範圍與操作權限。新增 adminRole 欄位至 DB schema。後端新增 adminCompanyProcedure、superAdminProcedure 細粒度權限中介層。新增管理員團隊頁面（/admin/team）：列表、新增/移除管理員、角色變更、超級管理員移轉。Admin Header Bar 加入語言切換、登出、返回主站。全站 EN/zh-TW 雙語。",
  },
  {
    version: "2.12.0",
    date: "2026-04-29",
    type: "minor",
    title: "Admin Panel 優化 — 豐富 Overview、分組 Sidebar、版本紀錄 + 架構頁面",
    description: "AdminOverview 新增 4 張統計卡片、方案分佈、快速操作、近期公司與活動表格。Sidebar 重構為 4 組分類導航（一般/管理/日誌/架構）+ i18n。新增 Version Log 頁面顯示 shared/changelog.ts 完整記錄。新增安全隱私架構頁面（加密、金鑰管理、實施狀態）與金流串接架構頁面。AdminTickets 修正為 AdminLayout。全站雙語 i18n。",
  },
  {
    version: "2.11.0",
    date: "2026-04-29",
    type: "minor",
    title: "AES-256-GCM 加密基礎架構 (Phase 1)",
    description: "新增 server/encryption.ts 核心模組（AES-256-GCM 欄位加密/解密、DEK cache、blind index）。新增 company_keys 表支援 per-company 獨立加密金鑰。公司建立時自動產生 DEK。支援 AWS KMS 生產模式與本地開發模式。",
  },
  {
    version: "2.10.1",
    date: "2026-04-28",
    type: "patch",
    title: "修復 Admin 方案更新失敗 + toast 通知",
    description: "修正 adminUpdateCompanyPlan 的 Drizzle enum 型別問題，plan 欄位不再以 as any 繞過。Admin Companies 編輯對話框新增 success/error toast 通知。",
  },
  {
    version: "2.10.0",
    date: "2026-04-28",
    type: "minor",
    title: "Privacy Policy + Terms of Service 法律頁面",
    description: "新增 /privacy 隱私權政策與 /terms 服務條款頁面，完整雙語 i18n。Sidebar footer 新增 Privacy · Terms · © 2026 Caploom 連結列。Settings 側邊欄新增 Legal 入口。登入頁底部新增法律連結。所有角色皆可查閱法律頁面。",
  },
  {
    version: "2.9.0",
    date: "2026-04-28",
    type: "minor",
    title: "完整角色權限控管 (RBAC)",
    description: "六種公司角色（Owner / Admin / CFO / Lawyer / Investor / Viewer）各自擁有獨立的側邊欄、可訪問路由與操作權限。新增 shared/rolePermissions.ts 作為單一權限定義來源，RoleGuard 負責路由層級重導，ActionGuard 負責按鈕層級隱藏。Investor 登入後自動跳轉 Investor Portal。後端 mutation 已驗證皆有正確的 procedure guard。",
  },
  {
    version: "2.8.2",
    date: "2026-04-28",
    type: "patch",
    title: "Header 新增 Sign Out 圖示按鈕",
    description: "Desktop header 右上角新增 LogOut icon 按鈕，點擊即登出。Logout 現在同時出現在右上角 header 與左側 sidebar Account 兩處。CompanySwitcher 的 Sign out 文字也改用 i18n。",
  },
  {
    version: "2.8.1",
    date: "2026-04-28",
    type: "patch",
    title: "修復邀請加入後狀態停留 Pending 的問題",
    description: "Join 頁面原本僅做 read-only 驗證，未呼叫 acceptInvitation mutation 更新 DB。新增 useEffect 於使用者驗證 + 邀請有效時自動觸發 mutation，將 invitation status 更新為 accepted 並加入 company_members。新增接受中 / 失敗 UI 狀態與雙語 i18n。",
  },
  {
    version: "2.8.0",
    date: "2026-04-28",
    type: "minor",
    title: "Pricing 月付/年付切換 — 年繳 9 折優惠",
    description: "Pricing 頁面新增月付/年付 toggle switch，預設月付。切換至年付時自動計算 9 折價：Standard NT$269/月（年繳 NT$3,228，省 NT$360）、Plus NT$629/月（年繳 NT$7,548，省 NT$840）。綠色 badge 顯示「省 10%」，每張卡片下方顯示年繳總額與節省金額。Starter/Enterprise 不受影響。全站雙語 i18n。",
  },
  {
    version: "2.7.2",
    date: "2026-04-28",
    type: "patch",
    title: "電子簽名移回 Standard + 移除發送次數限制",
    description: "電子簽名從 Plus 移回 Standard（3 模板），Plus 升級為無限模板。移除 esignSendsPerMonth 限制（發送次數由 DocuSeal 管理，平台無法控制），僅保留模板數量限制。COMPARISON_TABLE 移除 esignSends 行，Subscription 用量改為顯示模板數。",
  },
  {
    version: "2.7.1",
    date: "2026-04-28",
    type: "patch",
    title: "用量限制下修 + 資料匯出 Starter 關閉",
    description: "公司數下修：Standard 1 間、Plus 3 間。股東人數下修：Starter 5 位、Standard 15 位、Plus 無限。資料匯出（PDF/Excel）從 Starter 移除，Standard 以上才有。同步更新 plans.ts limits + COMPARISON_TABLE、Pricing/Subscription i18n（EN/zh-TW）。",
  },
  {
    version: "2.7.0",
    date: "2026-04-28",
    type: "minor",
    title: "台幣定價策略 — NT$299/699 + 功能重新分配",
    description: "定價全面改為台幣計價：Starter NT$0、Standard NT$299/月（🔥 主打）、Plus NT$699/月（Anchor）、Enterprise 聯繫銷售。功能重新分配：Standard 著重無限股東、基本稀釋、台灣合規；Plus 升級為情境模擬、DCF、電子簽名（5 模板 30 次/月）、投資人入口；Enterprise 含 SSO、API、客製匯入。同步更新 COMPARISON_TABLE、Pricing 四欄、Subscription 用量限制、EN/zh-TW i18n。",
  },
  {
    version: "2.6.0",
    date: "2026-04-28",
    type: "minor",
    title: "DocuSeal 帳號串接 — Per-Company API Key + 引導流程",
    description: "eSignature 頁面新增帳號連線引導：未連結時顯示三步驟流程（註冊 DocuSeal → 複製 API Key → 貼上連線）。後端 docuseal.ts 重構為 per-company API key 架構，每間公司可獨立連結自己的 DocuSeal 帳號。新增 connect/disconnect/connectionStatus 三個 tRPC endpoint，API Key 存入 DB 前先驗證有效性。Header 顯示連線狀態 badge 與斷開連結功能。全站雙語 i18n。",
  },
  {
    version: "2.5.2",
    date: "2026-04-28",
    type: "patch",
    title: "合規功能分級調整 — 台灣合規→Standard，美國合規→Plus",
    description: "因主要 TA 為台灣新創，將技術股課稅與閉鎖性公司功能從 Plus 移至 Standard；409A 與 83(b) 從 Standard 移至 Plus（擴展美國市場階段）。同步更新 plans.ts feature sets、Compare Plans 比較表、Pricing 頁面 i18n。",
  },
  {
    version: "2.5.1",
    date: "2026-04-28",
    type: "patch",
    title: "修復舊方案值導致的 Runtime Crash",
    description: "新增 normalizePlan() 輔助函數，將 DB 中舊的方案值（free/paid/custom）自動對應至新的四級方案（starter/standard/enterprise）。修復 SubscriptionBadge、FeatureGate、Pricing、Subscription、Admin 頁面及 server context 共 8 處讀取 plan 值的位置，防止未知值導致 undefined 存取錯誤。",
  },
  {
    version: "2.5.0",
    date: "2026-04-28",
    type: "minor",
    title: "四級訂閱方案重構 — Starter / Standard / Plus / Enterprise",
    description: "訂閱方案從 Free/Pro/Enterprise 三級改為 Starter/Standard/Plus/Enterprise 四級。Standard 含限制模板電子簽名（3 模板、30 次/月）、瀑布分析、投資人入口；Plus 解鎖無限模板、DCF 預測、反稀釋模型、台灣合規；Enterprise 含 SSO、API、專屬客戶經理。DB enum、plans.ts、Pricing 四欄、Compare Plans 五欄、FeatureGate、SubscriptionBadge、Admin 面板全站更新。",
  },
  {
    version: "2.4.0",
    date: "2026-04-28",
    type: "minor",
    title: "Landing Page Quick Start Guide — 新手引導流程",
    description: "重新設計空白狀態首頁：新增 5 步驟 Quick Start 指引（公司設定 → 投資人 → 募資輪次 → ESOP → Cap Table），附帶步驟編號、垂直連接線與 hover CTA。底部提示列含 Excel 匯入捷徑。下方保留 3×3 功能探索卡片。全站雙語 i18n。",
  },
  {
    version: "2.3.0",
    date: "2026-04-28",
    type: "minor",
    title: "Help & Support — FAQ + Feedback + 聯繫客服",
    description: "新增 /help 頁面含三個分頁：分類 FAQ（帳戶/訂閱/股權/技術/一般）含搜尋；意見回饋表單（feedback/feature request/bug）；聯繫客服表單（帳單/技術/客製化需求）含優先級。Header 新增問號 icon。Support tickets 存入 DB 並在 Admin Panel 新增工單管理頁。全站雙語 i18n（support namespace）。",
  },
  {
    version: "2.2.1",
    date: "2026-04-28",
    type: "patch",
    title: "Pricing / Compare Plans 頁面拆分",
    description: "將原本合併在 Pricing 頁的功能比較表拆為獨立 /compare-plans 頁面。Subscription 頁「比較方案」按鈕導向 /compare-plans，「變更方案」導向 /pricing。FeatureGate overlay 同步更新連結。",
  },
  {
    version: "2.2.0",
    date: "2026-04-28",
    type: "minor",
    title: "訂閱方案功能分級 — Feature Gating + 用量限制",
    description: "新增 shared/plans.ts 定義三級方案功能矩陣與用量上限。後端 planGuard middleware 攔截受限 API（14 個模組）；前端 FeatureGate 元件對 16 個頁面加上模糊升級覆蓋層。Pricing 頁新增完整功能比較表，Subscription 頁新增「比較方案」按鈕。Create 操作（股東、ESOP、公司、團隊邀請）加入用量檢查。",
  },
  {
    version: "2.1.0",
    date: "2026-04-28",
    type: "minor",
    title: "訂閱方案 — Badge + Pricing + Subscription 頁面",
    description: "右上角 Header 新增方案 Badge（Free/Pro/Enterprise），點擊進入訂閱管理頁。新增 Pricing 三欄比較頁（功能清單、升級 CTA）與 Subscription 管理頁（目前方案、使用量進度條、帳單區塊）。全站雙語 i18n（subscription namespace）。",
  },
  {
    version: "2.0.0",
    date: "2026-04-28",
    type: "major",
    title: "Layout 重構 — Content Header + Sidebar 精簡",
    description: "新增內容區頂部 Header Bar：Caploom logo、Admin Panel、語言切換、通知鈴鐺、登出。Sidebar Header 改為 CompanySwitcher（左）+ 收合按鈕（右）+ 使用者資訊（從 footer 上移）。Sidebar Footer 精簡為僅 VersionBadge。Mobile header 維持不變。",
  },
  {
    version: "1.23.2",
    date: "2026-04-28",
    type: "patch",
    title: "ClosedCompany 配置統一 + Rounds i18n 修復",
    description: "閉鎖性公司管理頁面改為與其他頁面一致的配置（p-8 max-w-6xl、inline icon、semantic token）。募資輪次頁面完成全欄位 i18n：新增 fundraising namespace hook、表格標頭、對話框、表單欄位、狀態 Badge、toast 訊息、刪除確認等全部改用 t() 呼叫。",
  },
  {
    version: "1.23.1",
    date: "2026-04-28",
    type: "patch",
    title: "ESOP 頁面 i18n 修復",
    description: "修復 ESOP 頁面 50+ 個硬編碼英文字串未連接翻譯系統的問題。KPI 卡片、表格標題、對話框、表單欄位、空白狀態、toast 訊息、行使流程等全部改用 t() 呼叫。新增 70 個 esop.* 翻譯鍵至 equity namespace。語言切換現在完整涵蓋 ESOP 所有 UI 元素。",
  },
  {
    version: "1.23.0",
    date: "2026-04-27",
    type: "minor",
    title: "i18n Phase 6 — 剩餘頁面 + 共用元件全站翻譯完成",
    description: "完成全站 i18n：Home Dashboard、EstimatedValuation、ShareClasses、Join、NotFound 五個頁面，以及 AllocationDialog、CompanySwitcher、NotificationBell、ChangelogDrawer、VestingTimeline 五個共用元件。新增 200+ 翻譯鍵至 pages / common namespace，涵蓋 KPI 卡片、圖表、漏斗、空白狀態、功能卡片、表單欄位等所有 UI 文字。全站零硬編碼字串。",
  },
  {
    version: "1.22.0",
    date: "2026-04-27",
    type: "minor",
    title: "i18n Phase 5 — Settings & Admin 全模組翻譯",
    description: "新增 settings / admin 兩個 namespace，完成 7 個頁面全欄位 i18n：AuditLog、Import、Team、Snapshots、AdminOverview、AdminCompanies、AdminActivity。稽核日誌、資料匯入、角色權限、團隊管理、快照操作、平台管理等 150+ 個翻譯鍵皆支援語言切換。",
  },
  {
    version: "1.21.0",
    date: "2026-04-27",
    type: "minor",
    title: "i18n Phase 4 — Equity, Fundraising & Analysis 全模組翻譯",
    description: "新增 equity / fundraising / analysis 三個 namespace，完成 12 個頁面全欄位 i18n：CapTable、ShareRegister、ESOP、ESign、FundingRounds、RoundDetail、Investors、Instruments、Waterfall、Valuation、Projections、AntiDilution。所有表單、表格、對話框、按鈕、模擬器皆支援語言切換。",
  },
  {
    version: "1.12.0",
    date: "2026-04-25",
    type: "minor",
    title: "Admin panel",
    description: "Platform admin backend — company management with subscription tiers (Free/Paid/Custom), audit log viewer, plan editor, suspend/reactivate, and admin activity tracking.",
  },
  {
    version: "1.11.0",
    date: "2026-04-25",
    type: "minor",
    title: "Navigation redesign",
    description: "Streamlined sidebar from 18 flat items to 6 collapsible groups — Dashboard, Equity, Fundraising, Analysis, Investor Portal, Settings — with auto-expanding active section.",
  },
  {
    version: "1.10.0",
    date: "2026-04-25",
    type: "minor",
    title: "Investor portal",
    description: "Dedicated read-only view for investors — see holdings by share class, ESOP vesting timeline, download share certificates, and track document signing status.",
  },
  {
    version: "1.9.0",
    date: "2026-04-25",
    type: "minor",
    title: "Share certificate PDF",
    description: "Generate formal share certificates from any issuance or ESOP exercise entry — includes company branding, certificate number, share details, and authorized signatory block.",
  },
  {
    version: "1.8.0",
    date: "2026-04-25",
    type: "minor",
    title: "Vesting schedule visualization",
    description: "Click any ESOP grant to expand an interactive vesting timeline — area chart with cliff/today markers, progress bar, and milestone cards.",
  },
  {
    version: "1.7.0",
    date: "2026-04-25",
    type: "minor",
    title: "ESOP exercise flow",
    description: "Exercise vested options into Common Stock with one click — atomically updates grant, writes to share register, and triggers cap table snapshot.",
  },
  {
    version: "1.6.0",
    date: "2026-04-25",
    type: "minor",
    title: "Investor portal",
    description: "投資人登入後可以查看持股、vesting 進度和文件簽署狀態。",
  },
  {
    version: "1.5.1",
    date: "2026-04-24",
    type: "patch",
    title: "Share class cleanup",
    description: "Removed ESOP from share class options — ESOP exercises into Common Stock. Corrected share class dropdown to show Common/Preferred only.",
  },
  {
    version: "1.5.0",
    date: "2026-04-24",
    type: "minor",
    title: "Data export",
    description: "Cap table PDF/Excel and share register Excel export with formatted workbooks, frozen headers, and dynamic share class names.",
  },
  {
    version: "1.4.0",
    date: "2026-04-24",
    type: "minor",
    title: "Share class management",
    description: "Define equity classes with preferred terms — liquidation multiple, participation type, anti-dilution, dividends, voting rights, and conversion ratio.",
  },
  {
    version: "1.3.0",
    date: "2026-04-24",
    type: "minor",
    title: "eSignature template library",
    description: "Two-layer template system: platform-wide templates for all companies and company-scoped templates for custom contracts.",
  },
  {
    version: "1.2.0",
    date: "2026-04-24",
    type: "minor",
    title: "DocuSeal eSignature",
    description: "Send equity documents for signing via DocuSeal — create templates from PDF/DOCX, track signing status, and receive webhook notifications.",
  },
  {
    version: "1.1.1",
    date: "2026-04-23",
    type: "patch",
    title: "Mobile responsive layout",
    description: "Bottom navigation bar, scrollable tables, and responsive grid layouts for mobile devices.",
  },
  {
    version: "1.1.0",
    date: "2026-04-22",
    type: "minor",
    title: "Instruments — SAFE & Convertible Notes",
    description: "Track SAFEs and convertible notes with conversion modeling, interest accrual, and batch conversion to equity.",
  },
  {
    version: "1.0.0",
    date: "2026-04-20",
    type: "major",
    title: "Caploom v1 launch",
    description: "Cap table, share register, funding rounds, investor pipeline, ESOP management, waterfall analysis, financial projections, and audit logging.",
  },
];

/** Current version — always the first entry. */
export const CURRENT_VERSION = CHANGELOG[0].version;
