/**
 * Caploom Changelog — single source of truth for versioning.
 *
 * HOW TO UPDATE:
 *   1. Add a new entry at the TOP of the `CHANGELOG` array
 *   2. Bump the version number following semver:
 *      - major: platform architecture redesign (1.x → 2.x)
 *      - minor: new feature (+0.1.0)
 *      - patch: bug fix / tweak (+0.0.1)
 *   3. The frontend reads CHANGELOG[0] to display the current version
 */

export type ChangelogEntry = {
  version: string;          // "1.4.0"
  date: string;             // "2026-04-24"
  type: "major" | "minor" | "patch";
  title: string;            // short headline
  description: string;      // 1-2 sentence summary
};

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: "2.65.0",
    date: "2026-07-14",
    type: "minor",
    title: "P3 架構強化 — CSP Security Headers + 加密聚合重構",
    description: "安全 Headers：加入 CSP、X-Content-Type-Options、X-Frame-Options、HSTS、Referrer-Policy、Permissions-Policy。CSP 白名單涵蓋 Clerk/Sentry/Vercel Analytics。加密聚合重構：deriveCapTable 和 myHoldings 從 SQL SUM(plaintext) 改為 in-memory 聚合 decrypted 值，為後續移除明文欄位做準備。",
  },
  {
    version: "2.64.0",
    date: "2026-07-14",
    type: "minor",
    title: "P2 架構強化 — tRPC staleTime + Encryption 讀取路徑全面修補",
    description: "tRPC QueryClient 加入 staleTime 30s + refetchOnWindowFocus: false 減少冗餘 refetch。Encryption 收尾：修補 20 處讀取路徑缺口（db.ts / export.ts / capTable.ts / registerWrite.ts / routers.ts），所有 PII 與財務欄位現在優先從 _enc 欄位解密；投資人入口改用 blind index 查詢；docuseal disconnect 同步清除 _enc 欄位；匯出 decryptContactPii / decryptFinancialFields 供跨模組使用。",
  },
  {
    version: "2.63.0",
    date: "2026-07-13",
    type: "minor",
    title: "P1 架構強化 — DEK Cache 優化 + N+1 Query 修復 + Admin Security 強化",
    description: "DEK Cache：新增 getCachedDekIfValid() 跳過 DB 查詢直接取快取，resolveCompanyDek() 先查 cache 再 fallback。N+1 Query：antiDilution.trigger 改用 batchUpdateAntiDilutionProvisions() 交易式批次更新；investorPortal 4 個 endpoint 抽出 resolvePortalInvestor() 共用 helper 消除重複查詢。Admin Security：normalizeAdminRole() 預設改 admin（最小權限）；adminProcedure / adminCompanyProcedure / superAdminProcedure 加入 rateLimitApi middleware + FORBIDDEN 稽核日誌。",
  },
  {
    version: "2.62.0",
    date: "2026-07-09",
    type: "minor",
    title: "P0 架構強化 — Code Splitting + Rate Limiter + Sentry + DB Indexes",
    description: "效能：46 個頁面改為 React.lazy 動態載入，Vite manualChunks 拆分 8 個 vendor bundle（預期 FCP 12s→2-3s）。安全：Upstash Redis rate limiter（60 req/60s sliding window）。監控：Sentry 前後端錯誤追蹤 + Session Replay。資料庫：35+ 個 CONCURRENTLY 索引（SQL 腳本在 drizzle/add-indexes.sql）。",
  },
  {
    version: "2.61.0",
    date: "2026-05-13",
    type: "minor",
    title: "新公司註冊 Email 通知",
    description: "新增 Resend 信件通知功能：當有使用者透過 Onboarding Wizard 建立新公司時，系統自動發送 Email 通知平台管理員。Fire-and-forget 不阻塞主流程。",
  },
  {
    version: "2.60.2",
    date: "2026-05-13",
    type: "patch",
    title: "Admin Team — Super Admin 可管理其他 Super Admin",
    description: "修正 Admin Team 頁面權限邏輯：Super Admin 現在可以 Edit/Remove 其他 Super Admin（原本被限制只能管理 Admin 角色）。Transfer 仍僅對非 Super Admin 顯示。",
  },
  {
    version: "2.60.1",
    date: "2026-05-13",
    type: "patch",
    title: "Admin 新增支援 Super Admin 角色 & 修復建帳錯誤",
    description: "addAdmin API 與前端下拉選單支援 super_admin 角色。修復 adminCreateUser 因 lastSignedIn: null 違反 NOT NULL 約束導致建帳失敗的問題。",
  },
  {
    version: "2.60.0",
    date: "2026-05-13",
    type: "minor",
    title: "獨立 Admin 登入系統",
    description: "新增 /admin/login 獨立登入頁，Admin 不再需要前台帳號。支援 email 預建帳號、首次 Clerk 登入自動綁定 openId、admin-only 用戶自動導向後台。context.ts 新增 email 回填邏輯。",
  },
  {
    version: "2.59.0",
    date: "2026-05-13",
    type: "minor",
    title: "升級按鈕改為聯繫管理員 mailto",
    description: "Standard/Plus/Enterprise 的升級 CTA 從直接跳轉改為 mailto 連結，用戶需寄信申請手動升級。Landing page 同步更新，FAQ 說明調整。Pricing.tsx、FeatureGate.tsx 已含 mailto 邏輯。",
  },
  {
    version: "2.58.2",
    date: "2026-05-11",
    type: "patch",
    title: "QA Round 9 PR-2b — M10 通知查詢效能修正",
    description: "syncDeadlineNotifications 過去用 LIKE 全表掃 metadata 來 dedup，table 一大就慢。新增 notifications.source 欄位 + (companyId, source, createdAt) 複合索引；查詢改為 source = 'deadline' 直接走 index。INSERT 端同步寫入 source 欄位（deadline / broadcast）。Migration 0007 包含 backfill：舊 row 依 metadata 內容自動補上 source。",
  },
  {
    version: "2.58.1",
    date: "2026-05-11",
    type: "patch",
    title: "QA Round 9 PR-2a — High/Medium/Low 清理",
    description: "H5: 截止日通知 metadata 補上 messageEn/messageZh 雙語欄位，client 之後可依 locale 切換顯示。H7: Investors 頁面 7 個 icon-only 按鈕全部補上 aria-label（Edit/Delete activity + 月份切換）。M9: fundingRounds.create/update 的字串型金額欄位加 regex+max(40) 防 10MB 灌包。M11: Investors 列表 + 月曆 view 補上 isError 錯誤狀態 UI。L13: 移除 server/routers.ts 兩處 (x as any) 殘留（grant.sharesSettled、user.adminRole）。L14: server/db.ts broadcastNotification 用 InsertNotification 型別取代 `null as unknown as number` 強制轉型。M8（as any 大清掃）延後到專屬 PR。",
  },
  {
    version: "2.58.0",
    date: "2026-05-11",
    type: "minor",
    title: "QA Round 9 Critical — 補 migration、轉換失敗追蹤、advance compensating rollback、加密 logging",
    description: "C1: 補生 0006_aberrant_triton.sql migration（angel_tax_deductions / comps_peers / investor_activities / projection_scenarios + platform_broadcast / broadcast_notification enum 值），新環境 deploy 不會再 boot 就炸。C2: executeConversion 改成 per-instrument 結果追蹤 + idempotency（已 converted 跳過）+ 部分失敗回傳可重試清單；advance issued 路徑加 compensating rollback（writeRegisterEntry 失敗時還原 allocation 狀態）。H3: analysisRouter.analyze 從 protectedProcedure 改 companyProcedure。H6: 11 處 PII 加密的 silent catch 全換成 console.warn 帶錯誤訊息。",
  },
  {
    version: "2.57.0",
    date: "2026-05-10",
    type: "minor",
    title: "QA Round 8 — 殘留 i18n 清理",
    description: "Import.tsx 4 處 + AdminTemplates.tsx 3 處 toast 錯誤訊息遷移至 t()，新增 EN/zh-TW 翻譯鍵。",
  },
  {
    version: "2.56.0",
    date: "2026-05-10",
    type: "minor",
    title: "QA Round 7 — i18n 遷移 + 響應式表格修復",
    description: "AntiDilution/Instruments/Import/Snapshots/AuditLog/RoundDetail/AdminTickets 共 ~35 處硬編碼英文字串遷移至 t()、7 個頁面表格加入 overflow-x-auto 手機適配。",
  },
  {
    version: "2.55.0",
    date: "2026-05-10",
    type: "minor",
    title: "QA Round 6 — Delete 函數防護 + 計算引擎防護",
    description: "deleteEsopPoolV1/deleteEsopGrantV1/deleteInstrument/deleteShareClass 加入子記錄 pre-delete guard 防止孤立資料、compsCalc computeStats 空陣列除零防護。",
  },
  {
    version: "2.54.0",
    date: "2026-05-10",
    type: "minor",
    title: "QA Round 5 — 安全防護 + i18n + 錯誤處理 + 資料完整性",
    description: "deleteAllocation 加入子記錄防護防止孤立帳本、ESign/CompanySettings/Waterfall 全面 i18n 遷移（~60+ 處）、11 個頁面補齊 isError 錯誤處理、自由文字 Zod 欄位加 .max() 限制、capTable 過濾負數持股、buildSnapshotName 補齊 rsu_settlement 動詞。",
  },
  {
    version: "2.53.2",
    date: "2026-05-10",
    type: "patch",
    title: "修正 Deadline 函數 12 處 TypeScript 型別錯誤",
    description: "getUpcomingDeadlines 中的 shareholderName / employeeName / instrumentName / instrumentType / signerName 全部替換為實際 schema 欄位（holderName, name, type, title, shareholderId），消除所有 TypeScript 編譯錯誤。",
  },
  {
    version: "2.53.1",
    date: "2026-05-10",
    type: "patch",
    title: "RegisterEntryInput eventType 同步 rsu_settlement",
    description: "RegisterEntryInput 型別新增 rsu_settlement，signedShareCount switch 補齊對應 case，移除 routers.ts 中 eventType 的 as any 強制轉型。",
  },
  {
    version: "2.53.0",
    date: "2026-05-09",
    type: "minor",
    title: "安全性 & 資料完整性修復 — 後端 API 掃描",
    description: "修復 9 項安全與資料一致性問題：PII 欄位讀取時自動解密（shareholders/investors/company）、companies.get 與 auth.me 移除敏感欄位回傳、delete investor/round/shareholder 加入子記錄防護、fileBase64 加入 10MB 上限、auditLog limit 加入 max(500)、deleteAccountCascade 補齊 auditLogs/supportTickets 清理、truncateAllBusinessData 補 supportTickets、PLATFORM_OWNER_EMAIL 改用環境變數。",
  },
  {
    version: "2.52.0",
    date: "2026-05-09",
    type: "minor",
    title: "QA 修復 — XSS 消除、i18n 遷移、響應式 & error state 補齊",
    description: "移除 Join/AllocationDialog/EstimatedValuation 的 dangerouslySetInnerHTML 改用 Trans 元件；AngelTaxDeduction 全頁遷移至 t() 系統（43 keys）；Home.tsx sidebar cards i18n 化（12 keys）；AuditLog/Waterfall 加入 error state；ShareTransfers 響應式修復；DashboardLayout 硬編碼字串 i18n 化。",
  },
  {
    version: "2.51.0",
    date: "2026-05-09",
    type: "minor",
    title: "Vercel Speed Insights 整合",
    description: "安裝 @vercel/speed-insights 套件並在 App.tsx 加入 <SpeedInsights/> 元件，啟用 Real Experience Score（FCP、LCP、INP、CLS）效能追蹤。同步在 Vercel Dashboard 啟用 Landing Page Web Analytics 及 App Speed Insights。",
  },
  {
    version: "2.50.1",
    date: "2026-05-07",
    type: "patch",
    title: "Fix: Admin 版本紀錄整合雙 Changelog + 通知頁面 padding 對齊",
    description: "Admin 版本紀錄頁面改為 Tab 切換，同時顯示前臺（Platform）與後臺（Admin Panel）兩份 Changelog。Overview 頁面同時展示兩者最新版本。通知管理頁面補上 p-8 max-w-6xl mx-auto wrapper 對齊其他頁面。補齊 adminChangelog.ts 缺漏的 v1.9.0~v1.12.0 四個版本。",
  },
  {
    version: "2.50.0",
    date: "2026-05-07",
    type: "minor",
    title: "Admin Broadcast Notifications — 平台級廣播通知",
    description: "新增後臺管理廣播通知功能：管理員可一鍵向所有公司發送站內 / Email / 雙管道通知。含發送表單、頻道選擇、歷史記錄，並整合 platform_broadcast 通知類型。",
  },
  {
    version: "2.49.1",
    date: "2026-05-07",
    type: "patch",
    title: "Fix RBAC — 補齊新功能頁面角色權限",
    description: "修正 CFO / Viewer / Lawyer 角色無法存取 /comps（可比公司分析）、/angel-tax（天使投資抵減）、/compare-plans 等新增頁面的權限白名單遺漏。同步修正 CompanySettings Danger Zone i18n namespace 問題。",
  },
  {
    version: "2.49.0",
    date: "2026-05-07",
    type: "minor",
    title: "Demo Data Pack — Full Export/Import for 25+ Tables",
    description: "新增 Demo Data Pack 功能：一鍵匯出所有業務資料（投資人、輪次、股權、ESOP、合規、分析等 25+ 張表）為多 Sheet Excel。可匯入至全新帳號完整還原所有 demo 內容。修正 truncateAllBusinessData 遺漏 8 張表的問題。",
  },
  {
    version: "2.48.2",
    date: "2026-05-07",
    type: "patch",
    title: "Investor view toggle — prominent tab bar",
    description: "視圖切換按鈕從右上角小圖示改為標題下方的醒目 Tab Bar（含圖示+文字標籤），切換 List/Board/Calendar 更直覺。",
  },
  {
    version: "2.48.1",
    date: "2026-05-07",
    type: "patch",
    title: "Fix allocation→investor status sync + seed investor activities",
    description: "修正 ALLOC_TO_INVESTOR mapping（pledged→committed）。新增 seed script 同步投資人狀態（根據 allocation 進度）並為 8 位 funnel 投資人補上完整 Activity 歷程記錄。",
  },
  {
    version: "2.48.0",
    date: "2026-05-07",
    type: "minor",
    title: "Investor CRM — Unified 3-View Page + Board Kanban + Status Auto-Sync",
    description: "投資人頁面統一為三視圖（列表/看板/日曆），Pipeline 日曆併入 Investors 頁面。新增 Board View 看板（5 欄 Kanban，一鍵推進狀態）。Allocation 推進時自動同步投資人狀態（pledged→Meeting, signed→Term Sheet, funded/issued→Invested）。側邊欄精簡為 3 項。",
  },
  {
    version: "2.47.0",
    date: "2026-05-07",
    type: "minor",
    title: "Investor CRM — Activity Timeline, Pipeline Calendar & Dashboard",
    description: "投資人 CRM 前端完整上線：投資人列表可展開內嵌活動時間軸（待處理/已完成分區、逾期高亮、類型與優先級徽章）；全新管線日曆頁面（月檢視、活動分日顯示、30 天即將到來列表）；Dashboard 右側新增即將到來活動卡片。",
  },
  {
    version: "2.46.0",
    date: "2026-05-07",
    type: "minor",
    title: "Investor CRM Activities — Backend Foundation",
    description: "投資人 CRM 活動追蹤後端。新增 investor_activities 資料表（會議、文件、跟進、電話、備忘等 8 種類型），含 CRUD tRPC 路由、狀態/優先級/到期日篩選、自動更新 lastContactAt。",
  },
  {
    version: "2.45.0",
    date: "2026-05-07",
    type: "minor",
    title: "Active Deadline Notifications — Auto-Sync on Login",
    description: "主動通知系統。Dashboard 載入時自動掃描 60 天內到期事項，依 deadlineId + severity 去重後建立站內通知。嚴重度升級（warning → urgent）時再次通知。右側面板持續顯示待處理事項。",
  },
  {
    version: "2.44.0",
    date: "2026-05-07",
    type: "minor",
    title: "Unified Deadline Reminders — Dashboard Widget",
    description: "統一到期提醒系統。後端掃描 9 類時間敏感事件（409A / 83b / 技術股 / 天使稅 / ESOP 到期 / 閉鎖期 / 到期日 / ROFR / 電子簽署），前端 Dashboard 新增 Upcoming Deadlines 卡片，依緊急度分色（urgent ≤14d / warning ≤60d / info），點擊直接跳轉對應頁面。",
  },
  {
    version: "2.43.0",
    date: "2026-05-07",
    type: "minor",
    title: "Angel Investor Tax Deduction Tracker (§23-2)",
    description: "新增天使投資人租稅優惠追蹤功能（產創條例 §23-2）。包含 DB schema、後端 tRPC routes、前端頁面（摘要卡片 + 篩選 + 資料表格）、Sidebar 導航、i18n、13 筆 demo seed data（8 適用 + 5 不適用）。支援閉鎖期倒數、退稅年度計算、投資人提醒功能。",
  },
  {
    version: "2.42.0",
    date: "2026-05-07",
    type: "minor",
    title: "Analysis Demo Data Seed Script",
    description: "新增 scripts/seed-analysis-demo.ts，為 Analysis 模組 5 個頁面植入展示資料：Financial Projections（Biotech SaaS 五年預測）、3 個 Projection Scenarios（Base/Optimistic/Conservative）、5 家台灣上市生技公司 Comps Peers（合一/藥華藥/智擎/保瑞/晟德）、Liquidation Preferences（Pre-Seed/Seed/Series A）、Anti-Dilution Provisions（BBWA + Full Ratchet）。腳本完全冪等，可重複執行。",
  },
  {
    version: "2.41.0",
    date: "2026-05-06",
    type: "minor",
    title: "Frontend Wiring — Scenario Save + Export Buttons + Comps Export",
    description: "將匯出按鈕整合到 Projections DCF Tab（Export DCF PDF/Excel）、Three-Statement Tab（Export Three-Statement PDF/Excel）及 CompsAnalysis 頁面（Export Comps PDF/Excel）。P&L Tab 加入 Save as Scenario 按鈕，將當前假設儲存至 Scenario Manager。完整 i18n 支援（scenario.saved / enterName / bestCase 等鍵值）。",
  },
  {
    version: "2.40.0",
    date: "2026-05-06",
    type: "minor",
    title: "PDF & Excel Export — DCF, Comps, Three-Statement Financial Analysis",
    description: "新增分析報表匯出功能。建立 client/src/utils/analysisExport.ts 模組，提供 6 個匯出函式：exportDcfPdf / exportDcfExcel（DCF 估值報告）、exportCompsPdf / exportCompsExcel（對標公司分析）、exportThreeStatementPdf / exportThreeStatementExcel（三表財務模型）。PDF 使用 jsPDF + jspdf-autotable，包含執行摘要、假設、FCF 投影、敏感性矩陣；Excel 採 ExcelJS，每份報告含 2-3 個工作表（摘要、詳細資料、敏感性）。完整格式化（NT$ 貨幣、百分比、倍數）及 EN/zh-TW i18n 支援。",
  },
  {
    version: "2.39.0",
    date: "2026-05-06",
    type: "minor",
    title: "Scenario Manager — Save & Compare Multiple Projection Scenarios",
    description: "新增情景管理器功能：新 projection_scenarios DB 表存儲假設快照。DB 層 (db.ts) 新增 CRUD 函數；tRPC 路由 scenario.list / .get / .create / .update / .delete；前端 UI 於 Projections 頁頂部加入情景選擇器 + Save as Scenario 按鈕 + Compare 按鈕；Compare 對話框並排展示 2-3 個情景的關鍵指標 (營收、EBITDA、淨利、自由現金流)。完整 EN/zh-TW i18n 支援。",
  },
  {
    version: "2.38.0",
    date: "2026-05-06",
    type: "minor",
    title: "ClosedCompany Share Rights Export — PDF + Excel",
    description: "閉鎖性公司特別股頁面新增 PDF 與 Excel 匯出功能。PDF 匯出使用 jsPDF + jspdf-autotable，含公司名稱、特別股權利對照表及生成時間。Excel 匯出使用 ExcelJS，支援標題列著色、交替列底色、自動欄寬。匯出按鈕於有股份類別時出現。完整 EN/zh-TW i18n 支援。",
  },
  {
    version: "2.37.0",
    date: "2026-05-06",
    type: "minor",
    title: "Encryption Dual-Write Migration Finalization",
    description: "完成加密雙寫遷移收尾工作。所有 READ 函數已驗證正確解密加密欄位（users, companies, shareholders, allocations, shareRegisterEntries, instruments, shareTransfers, esopGrantsV1）。新增 migrateEncryptionForCompany(companyId) 遷移助手函數，讀取所有公司資料，對加密欄位為 NULL 但明文存在的列加密並回填。新增 admin tRPC endpoint encryption.migrateCompany (superAdminProcedure)，執行遷移並記錄稽核日誌，回傳遷移統計報告（per table migrated count、errors、summary）。",
  },
  {
    version: "2.36.0",
    date: "2026-05-06",
    type: "minor",
    title: "Account Termination / Delete Feature — Complete Account & Data Cascade Deletion",
    description: "Settings → Danger Zone 新增帳號刪除功能：後端 deleteAccountCascade 函式執行級聯刪除 (notifications, company_members, users)，deleteMyAccount tRPC endpoint 驗證郵件確認，前端確認對話框需輸入電郵驗證。刪除帳號後自動重導首頁。完整 EN/zh-TW i18n 支援。",
  },
  {
    version: "2.35.0",
    date: "2026-05-06",
    type: "minor",
    title: "Tech Share Tax Calculator — 台灣 §19-1 緩課試算",
    description: "新增技術股 / RSA 課稅試算功能：純 TypeScript 計算引擎 (calculateTechShareTax) 實作 §19-1 所得緩課規則、取得時所得、Vesting 所得、處分損益、應稅所得合計與 20% 預估稅額。TaxCalculationCard 元件展示可折展試算細節，支援 NT$ 貨幣格式、顏色編碼（綠：緩課，紅：應稅，琥珀：風險），完整 EN/zh-TW i18n。TechShareTax 頁面整合試算卡、表格列可點選檢視試算結果。",
  },
  {
    version: "2.34.0",
    date: "2026-05-06",
    type: "minor",
    title: "Recharts Interactive Charts — P&L, BS Composition, Cash Flow, DCF Terminal Value",
    description: "Projections 頁面新增 4 組交互式 Recharts 圖表：P&L tab 的 Revenue & Profitability (ComposedChart)，Three-Statement tab 的 Balance Sheet Composition (BarChart)、Cash Flow Trend (ComposedChart with line overlay)，DCF tab 的 Terminal Value % of EV (Donut chart)。所有圖表 i18n 支援 (EN + zh-TW)，NT$ 貨幣格式化，ResponsiveContainer 自適應寬度。",
  },
  {
    version: "2.33.3",
    date: "2026-05-06",
    type: "patch",
    title: "QA Round 5 H/M/L — schema hardening, type safety, validation",
    description: "C3: comps_peers.companyId 補上 .notNull()。H2: 移除 CompsAnalysis/Projections 的 as any、(p: any)，改用 inferRouterOutputs 跟具名 type。H3+M4: comps router 的 ticker 加 .max(20)，revenue/marketCap 加 .min(0)。M2: dcfCalc sensitivity header 改用 exhaustive switch + never check。M3: CompsAnalysis 補 isLoading 顯示。M5: WACC 全 input clamp 到合理範圍並警告。L4: netPPE clamp 到 >= 0。L5: sensitivity WACC row floor 到 baseGrowth + 0.5%，避免 r ≤ g 產生 TV=0。",
  },
  {
    version: "2.33.2",
    date: "2026-05-06",
    type: "patch",
    title: "QA Round 5 Critical — DCF EV→Equity bridge & Three-Statement BS balance",
    description: "修復兩個會直接影響財務數字正確性的計算錯誤：(1) DCF 的 EV→Equity bridge 之前同時減 netDebt 又加 cash，導致 equity 被高估（因為 netDebt 已含 cash 抵）— 移除重複的 + cash，並隱藏 cash 欄位、為 netDebt 加 hint。(2) Three-Statement Model 的 Year 1 開帳缺 commonStock，導致 isBalanced 永遠為 false — 補上 commonStock = initialCash − initialDebt 作為期初股本。Mid-year 折現對 TV 改為 n − 0.5 期。",
  },
  {
    version: "2.33.1",
    date: "2026-05-06",
    type: "patch",
    title: "Fix ESign.tsx TypeScript errors — missing useTranslation hook",
    description: "修復 ESign.tsx 中 RequestsSection 元件缺少 useTranslation('equity') hook 導致的 8 個 TS2304 編譯錯誤。",
  },
  {
    version: "2.33.0",
    date: "2026-05-06",
    type: "minor",
    title: "Comps Analysis + Three-Statement Model",
    description: "新增可比公司分析 (Comparable Companies Analysis)：同業 EV/Revenue、EV/EBITDA、P/E 倍數比較，含統計摘要 (min/Q1/median/mean/Q3/max) 與隱含估值。新增三表聯動模型 (Three-Statement Model)：損益表 → 資產負債表 → 現金流量表，A/R Days、Inventory Days、A/P Days 驅動，自動交叉驗證 Assets = Liabilities + Equity。含 DB schema (compsPeers)、tRPC 路由、完整 i18n 支援。",
  },
  {
    version: "2.32.0",
    date: "2026-05-06",
    type: "minor",
    title: "DCF Professional Upgrade — WACC via CAPM, Dual TV, Sensitivity Table",
    description: "新增 WACC 計算引擎 (CAPM: Rf + β×ERP)、終端價值雙方法 (Gordon Growth + Exit Multiple)、年中折現慣例、EV→Equity 橋接明細（含少數股權/特別股）、5×5 敏感度分析熱力圖。DCF Tab UI 全面升級。i18n EN + zh-TW 完整支援。",
  },
  {
    version: "2.31.3",
    date: "2026-05-06",
    type: "patch",
    title: "QA Round 4 — Medium & Low severity fixes",
    description: "Medium: AllocationDialog placeholders i18n 化、ESign 表單重設時序修正、CompanySettings useEffect 依賴修正、ESign/RoundDetail icon-only 按鈕加 aria-label、DB list query 加 LIMIT、delete 函數加 cascade risk 註解。Low: EstimatedValuation 移至 components/、刪除 ComponentShowcase 孤立檔、移除 console.log 殘留。",
  },
  {
    version: "2.31.2",
    date: "2026-05-06",
    type: "patch",
    title: "QA Round 4 — High severity fixes",
    description: "Nav: split single Legal item into Privacy + Terms (sidebar + mobile). Backend: allocation advance race condition fix with post-update verification for all state transitions. Audit: platform template operations now log companyId: 0. i18n: replaced hardcoded English toast messages in ESign (4), CompanySettings (1), Team (3) with react-i18next EN/zh-TW translations.",
  },
  {
    version: "2.31.1",
    date: "2026-05-06",
    type: "patch",
    title: "Security — QA Round 4 critical fixes",
    description: "Fixed cross-tenant signing template access (getTemplate now filters by companyId). Strengthened allocation create form validation and double-submit prevention. Hardened transfer ownership confirmation guard.",
  },
  {
    version: "2.31.0",
    date: "2026-05-05",
    type: "minor",
    title: "Allocation — Skip Term Sheet option",
    description: "Added 'Skip (no term sheet)' checkbox to the allocation edit dialog. When checked, the term sheet URL requirement is bypassed for advancing to Committed. Agreement URL remains mandatory.",
  },
  {
    version: "2.30.3",
    date: "2026-05-05",
    type: "patch",
    title: "Allocation — Move Advance into Edit dialog",
    description: "Removed the standalone Advance button from the allocation table. Advance is now only available inside the Edit dialog, where required fields (term sheet URL, etc.) can be filled first. Advance auto-saves the form before advancing.",
  },
  {
    version: "2.30.2",
    date: "2026-05-05",
    type: "patch",
    title: "Team — Delete invitation records",
    description: "Admins can now permanently delete any invitation record (pending, revoked, accepted, or expired) from the Team management page.",
  },
  {
    version: "2.30.1",
    date: "2026-05-05",
    type: "patch",
    title: "修復團隊邀請 — 登入後自動回到 Join 頁完成 accept",
    description: "修正邀請連結登入後導向首頁、未回到 /join?token= 導致 acceptInvitation 未觸發的問題。改用 Clerk openSignIn 搭配 afterSignInUrl 確保登入後回到 Join 頁自動完成接受流程。",
  },
  {
    version: "2.30.0",
    date: "2026-05-05",
    type: "minor",
    title: "Dashboard 重新排版 — 三區制 + Fundraising Goal",
    description: "Dashboard 全面重新排版：Zone 1 KPI 卡片不變，Zone 2 Ownership Pie + Fundraising Summary（累計募資、最新估值、已結束輪次、投資人數），Zone 3 獨立 Fundraising Goal（進度條 + 狀態分佈 + 底部統計），Zone 4 簡化 All Rounds 表格。移除舊的 Valuation Bar Chart、Recent Allocations、RoundProgress 元件。",
  },
  {
    version: "2.29.0",
    date: "2026-05-05",
    type: "minor",
    title: "Dashboard 修正：表格對齊 + Pipeline 只顯示進行中 Round",
    description: "修正 Recent Activity allocation 表格 shares/amount 欄位標題與內容未對齊（CSS specificity 問題）。Pipeline Round Progress 改為只顯示未結束的 round，已 closed 的不再出現。新增 rebuild-allocations-from-register.ts 腳本從 Share Register 反推建立正確的 allocations。",
  },
  {
    version: "2.28.1",
    date: "2026-05-05",
    type: "patch",
    title: "移除 auto-seed 自動觸發，修正股東分配錯亂",
    description: "移除 router 中三處自動觸發（fundingRounds.list、allocations.list、register.list），防止頁面載入時隨機輪轉分配投資人到錯誤的 funding round。新增 cleanup-auto-seeded.ts 腳本清理被錯誤建立的 allocations、register entries 和 snapshots。",
  },
  {
    version: "2.28.0",
    date: "2026-05-05",
    type: "minor",
    title: "NTD/USD 幣別切換 + Register 自動同步",
    description: "RoundDetail、Home、ShareRegister 三個頁面的 Allocation 表格全面支援 NTD/USD 幣別切換。新增 Register 自動同步機制：載入 Share Register 頁面時自動檢測 issued allocation 並補建缺少的 register entry + snapshot，不再需要手動執行腳本。",
  },
  {
    version: "2.27.0",
    date: "2026-05-04",
    type: "minor",
    title: "RoundDetail i18n 修復 + Demo Allocation 金額調整腳本",
    description: "修復 RoundDetail 頁面 10 個缺漏的 i18n 翻譯鍵（EN/zh-TW），移除所有 fallback 硬編碼。新增 adjust-demo-allocations.ts 腳本，將 A Round 8 位投資人總額從 NT$1 億調整為 NT$6 千萬，保留 NT$4 千萬未認領。",
  },
  {
    version: "2.26.0",
    date: "2026-05-04",
    type: "minor",
    title: "首頁 Allocations 表格 + 募資輪進度卡片",
    description: "Allocations 表格獨立全寬顯示最近 6 筆分配明細。原 Allocation Funnel 的狀態摘要合併至新「募資輪進度」卡片頂部，下方依輪次顯示堆疊進度條、完成百分比與狀態圖例。",
  },
  {
    version: "2.25.0",
    date: "2026-05-04",
    type: "minor",
    title: "股東名冊日期排序",
    description: "股東名冊的篩選條件從「按投資人名稱」改為「日期排序」下拉選單，可選擇由新到舊或由舊到新排列，更符合實際使用需求。",
  },
  {
    version: "2.24.2",
    date: "2026-05-04",
    type: "patch",
    title: "Analysis i18n 完整化 + beta 標籤",
    description: "Projections、Waterfall、AntiDilution 三頁面所有 hardcoded 英文字串替換為 i18n 翻譯鍵（共 35+ 鍵）。Analysis 側邊欄群組加上 beta 下標。",
  },
  {
    version: "2.24.1",
    date: "2026-05-04",
    type: "patch",
    title: "Investor Portal — Contact Platform Admin + i18n",
    description: "Investor Portal 無存取權時改為聯絡平台管理員（mailto），不再顯示聯絡公司管理員。同時將頁面所有硬編碼英文字串 i18n 化（中英雙語）。",
  },
  {
    version: "2.24.0",
    date: "2026-05-04",
    type: "minor",
    title: "Admin: Delete Company (with confirmation)",
    description: "平台管理員可在後台永久刪除公司，需輸入完整公司名稱確認。刪除範圍涵蓋所有業務資料、團隊成員、加密金鑰與公司記錄本身。操作記錄於管理員稽核日誌。",
  },
  {
    version: "2.23.1",
    date: "2026-05-04",
    type: "patch",
    title: "Paid Plan Upgrade — Contact Admin Flow",
    description: "標準版與進階版升級按鈕改為 mailto 聯繫管理員，FeatureGate 升級按鈕同步改為寄信流程，企業版與頁尾「聯繫我們」也統一導向管理員信箱。",
  },
  {
    version: "2.23.0",
    date: "2026-05-04",
    type: "minor",
    title: "Security & Data Consistency Hardening",
    description: "移除 Team.tsx 全部 dangerouslySetInnerHTML 防止 XSS，改用安全的 React 元素插值；allocation advance 加入樂觀鎖防止並發雙重 issue；waterfall 計算 NaN 防護（liquidationMultiple null guard）。",
  },
  {
    version: "2.22.2",
    date: "2026-05-04",
    type: "patch",
    title: "QA Round 2 Fixes",
    description: "修正 Home.tsx setState-during-render（改用 useEffect）、Rounds 表單新增財務欄位驗證、ShareRegister toast 錯誤訊息加上前綴、Esop.tsx 6 處 title 屬性 i18n 化、ShareRegister 殘留英文全部替換為 t() 呼叫。",
  },
  {
    version: "2.22.1",
    date: "2026-05-04",
    type: "patch",
    title: "QA Fixes — Low Priority",
    description: "移除孤立檔案、NotFound 加 DashboardLayout、ESOP exercise/settle cache invalidation 修正、Export 按鈕 loading 閃現修復、Onboarding skip 持久化至 localStorage。",
  },
  {
    version: "2.22.0",
    date: "2026-05-04",
    type: "minor",
    title: "QA Fixes — Medium Priority",
    description: "表格手機端橫向捲動、OnboardingWizard 防閃爍 + 逾時處理、表單按鈕 pending 狀態、後端錯誤格式化、v1 頁面硬編碼字串全面 i18n 化。",
  },
  {
    version: "2.21.1",
    date: "2026-05-04",
    type: "patch",
    title: "QA Fixes — Critical & High Priority",
    description: "RoleGuard 安全性修補（阻擋無公司使用者直接進入頁面）、所有主要頁面加入 Error State、Admin 範本路由改用 adminProcedure、補齊遺漏 i18n 翻譯鍵。",
  },
  {
    version: "2.21.0",
    date: "2026-04-30",
    type: "minor",
    title: "Onboarding Wizard — 新使用者引導流程",
    description: "全新註冊使用者首次登入時，自動顯示引導精靈。透過簡潔的 2 步驟流程（公司名稱 + 英文名 + 統編 → 完成），快速建立公司並進入儀表板。支援中英雙語。",
  },
  {
    version: "2.20.1",
    date: "2026-04-30",
    type: "patch",
    title: "手機版改善 — 登出按鈕 + 更多選單完善",
    description: "手機版 header 新增登出按鈕。「更多」選單加入使用者資訊區塊（頭像 + 名稱 + 登出）、Compliance & Tax 完整導航、訂閱與說明入口。修正 Investors 頁面 15 個缺漏 i18n key。修正桌面版 signOut 翻譯 key 路徑。",
  },
  {
    version: "2.20.0",
    date: "2026-04-30",
    type: "minor",
    title: "平台範本管理 — Admin 後台統一管理電子簽名範本",
    description: "Admin Panel 新增 Templates 頁面。平台管理員可上傳、編輯、刪除合約範本，並依文件類型分類、設定最低方案門檻。公司端依訂閱方案即時可見對應範本，無需手動推送。",
  },
  {
    version: "2.19.0",
    date: "2026-04-30",
    type: "minor",
    title: "RSU（限制性股票單位）— Plus/Enterprise",
    description: "ESOP 頁面新增 Options/RSU 分頁切換。RSU 完整生命週期：Grant → Vest → 自動交割普通股至股東名冊。歸屬交割時自動計算台灣應稅所得（FMV × 交割股數）。功能僅限 Plus/Enterprise 方案。",
  },
  {
    version: "2.18.0",
    date: "2026-04-29",
    type: "minor",
    title: "Security Phase 5 — 金鑰輪替與稽核",
    description: "Super Admin 可於安全頁面一鍵輪替平台 DEK，所有輪替操作自動記錄至 admin audit log。安全架構五階段全數完成。",
  },
  {
    version: "2.17.0",
    date: "2026-04-29",
    type: "minor",
    title: "Security Phase 4 — DocuSeal API Key / Webhook Secret 加密",
    description: "DocuSeal API 金鑰與 webhook secret 加入 AES-256-GCM 加密雙寫，讀取時優先解密 _enc 欄位。",
  },
  {
    version: "2.16.0",
    date: "2026-04-29",
    type: "minor",
    title: "Security Phase 3 — 核心交易金額加密（AES-256-GCM 雙寫）",
    description: "allocations / shareRegisterEntries / instruments / shareTransfers 四張核心交易表的金額與股數欄位加入 AES-256-GCM 加密雙寫，共 22 個財務欄位。",
  },
  {
    version: "2.15.0",
    date: "2026-04-29",
    type: "minor",
    title: "Security Phase 2 — PII 欄位級加密（AES-256-GCM 雙寫模式）",
    description: "users / companies / shareholders / investors 四張表的 PII 欄位加入 AES-256-GCM 加密雙寫。新增 platform DEK、blind index（HMAC-SHA256）供加密後 email 查詢。",
  },
  {
    version: "2.14.0",
    date: "2026-04-29",
    type: "minor",
    title: "Admin RBAC 精簡為 2 角色（super_admin / admin）",
    description: "移除 support 與 viewer 兩個管理員角色，僅保留 super_admin 和 admin。精簡 DB enum、權限矩陣、團隊管理 UI 與 i18n 翻譯。",
  },
  {
    version: "2.13.0",
    date: "2026-04-29",
    type: "minor",
    title: "Admin RBAC 權限系統 — 4 角色 + 團隊管理頁面",
    description: "新增平台管理員 4 角色 RBAC（super_admin/admin/support/viewer），每角色有獨立的 sidebar 可視範圍與操作權限。新增 adminRole 欄位至 DB schema。後端新增 adminCompanyProcedure、superAdminProcedure 細粒度權限中介層。新增管理員團隊頁面（/admin/team）：列表、新增/移除管理員、角色變更、超級管理員移轉。Admin Header Bar 加入語言切換、登出、返回主站。全站 EN/zh-TW 雙語。",
  },
  {
    version: "2.12.0",
    date: "2026-04-29",
    type: "minor",
    title: "Admin Panel 優化 — 豐富 Overview、分組 Sidebar、版本紀錄 + 架構頁面",
    description: "AdminOverview 新增 4 張統計卡片、方案分佈、快速操作、近期公司與活動表格。Sidebar 重構為 4 組分類導航（一般/管理/日誌/架構）+ i18n。新增 Version Log 頁面顯示 shared/changelog.ts 完整記錄。新增安全隱私架構頁面（加密、金鑰管理、實施狀態）與金流串接架構頁面。AdminTickets 修正為 AdminLayout。全站雙語 i18n。",
  },
  {
    version: "2.11.0",
    date: "2026-04-29",
    type: "minor",
    title: "AES-256-GCM 加密基礎架構 (Phase 1)",
    description: "新增 server/encryption.ts 核心模組（AES-256-GCM 欄位加密/解密、DEK cache、blind index）。新增 company_keys 表支援 per-company 獨立加密金鑰。公司建立時自動產生 DEK。支援 AWS KMS 生產模式與本地開發模式。",
  },
  {
    version: "2.10.1",
    date: "2026-04-28",
    type: "patch",
    title: "修復 Admin 方案更新失敗 + toast 通知",
    description: "修正 adminUpdateCompanyPlan 的 Drizzle enum 型別問題，plan 欄位不再以 as any 繞過。Admin Companies 編輯對話框新增 success/error toast 通知。",
  },
  {
    version: "2.10.0",
    date: "2026-04-28",
    type: "minor",
    title: "Privacy Policy + Terms of Service 法律頁面",
    description: "新增 /privacy 隱私權政策與 /terms 服務條款頁面，完整雙語 i18n。Sidebar footer 新增 Privacy · Terms · © 2026 Caploom 連結列。Settings 側邊欄新增 Legal 入口。登入頁底部新增法律連結。所有角色皆可查閱法律頁面。",
  },
  {
    version: "2.9.0",
    date: "2026-04-28",
    type: "minor",
    title: "完整角色權限控管 (RBAC)",
    description: "六種公司角色（Owner / Admin / CFO / Lawyer / Investor / Viewer）各自擁有獨立的側邊欄、可訪問路由與操作權限。新增 shared/rolePermissions.ts 作為單一權限定義來源，RoleGuard 負責路由層級重導，ActionGuard 負責按鈕層級隱藏。Investor 登入後自動跳轉 Investor Portal。後端 mutation 已驗證皆有正確的 procedure guard。",
  },
  {
    version: "2.8.2",
    date: "2026-04-28",
    type: "patch",
    title: "Header 新增 Sign Out 圖示按鈕",
    description: "Desktop header 右上角新增 LogOut icon 按鈕，點擊即登出。Logout 現在同時出現在右上角 header 與左側 sidebar Account 兩處。CompanySwitcher 的 Sign out 文字也改用 i18n。",
  },
  {
    version: "2.8.1",
    date: "2026-04-28",
    type: "patch",
    title: "修復邀請加入後狀態停留 Pending 的問題",
    description: "Join 頁面原本僅做 read-only 驗證，未呼叫 acceptInvitation mutation 更新 DB。新增 useEffect 於使用者驗證 + 邀請有效時自動觸發 mutation，將 invitation status 更新為 accepted 並加入 company_members。新增接受中 / 失敗 UI 狀態與雙語 i18n。",
  },
  {
    version: "2.8.0",
    date: "2026-04-28",
    type: "minor",
    title: "Pricing 月付/年付切換 — 年繳 9 折優惠",
    description: "Pricing 頁面新增月付/年付 toggle switch，預設月付。切換至年付時自動計算 9 折價：Standard NT$269/月（年繳 NT$3,228，省 NT$360）、Plus NT$629/月（年繳 NT$7,548，省 NT$840）。綠色 badge 顯示「省 10%」，每張卡片下方顯示年繳總額與節省金額。Starter/Enterprise 不受影響。全站雙語 i18n。",
  },
  {
    version: "2.7.2",
    date: "2026-04-28",
    type: "patch",
    title: "電子簽名移回 Standard + 移除發送次數限制",
    description: "電子簽名從 Plus 移回 Standard（3 模板），Plus 升級為無限模板。移除 esignSendsPerMonth 限制（發送次數由 DocuSeal 管理，平台無法控制），僅保留模板數量限制。COMPARISON_TABLE 移除 esignSends 行，Subscription 用量改為顯示模板數。",
  },
  {
    version: "2.7.1",
    date: "2026-04-28",
    type: "patch",
    title: "用量限制下修 + 資料匯出 Starter 關閉",
    description: "公司數下修：Standard 1 間、Plus 3 間。股東人數下修：Starter 5 位、Standard 15 位、Plus 無限。資料匯出（PDF/Excel）從 Starter 移除，Standard 以上才有。同步更新 plans.ts limits + COMPARISON_TABLE、Pricing/Subscription i18n（EN/zh-TW）。",
  },
  {
    version: "2.7.0",
    date: "2026-04-28",
    type: "minor",
    title: "台幣定價策略 — NT$299/699 + 功能重新分配",
    description: "定價全面改為台幣計價：Starter NT$0、Standard NT$299/月（🔥 主打）、Plus NT$699/月（Anchor）、Enterprise 聯繫銷售。功能重新分配：Standard 著重無限股東、基本稀釋、台灣合規；Plus 升級為情境模擬、DCF、電子簽名（5 模板 30 次/月）、投資人入口；Enterprise 含 SSO、API、客製匯入。同步更新 COMPARISON_TABLE、Pricing 四欄、Subscription 用量限制、EN/zh-TW i18n。",
  },
  {
    version: "2.6.0",
    date: "2026-04-28",
    type: "minor",
    title: "DocuSeal 帳號串接 — Per-Company API Key + 引導流程",
    description: "eSignature 頁面新增帳號連線引導：未連結時顯示三步驟流程（註冊 DocuSeal → 複製 API Key → 貼上連線）。後端 docuseal.ts 重構為 per-company API key 架構，每間公司可獨立連結自己的 DocuSeal 帳號。新增 connect/disconnect/connectionStatus 三個 tRPC endpoint，API Key 存入 DB 前先驗證有效性。Header 顯示連線狀態 badge 與斷開連結功能。全站雙語 i18n。",
  },
  {
    version: "2.5.2",
    date: "2026-04-28",
    type: "patch",
    title: "合規功能分級調整 — 台灣合規→Standard，美國合規→Plus",
    description: "因主要 TA 為台灣新創，將技術股課稅與閉鎖性公司功能從 Plus 移至 Standard；409A 與 83(b) 從 Standard 移至 Plus（擴展美國市場階段）。同步更新 plans.ts feature sets、Compare Plans 比較表、Pricing 頁面 i18n。",
  },
  {
    version: "2.5.1",
    date: "2026-04-28",
    type: "patch",
    title: "修復舊方案值導致的 Runtime Crash",
    description: "新增 normalizePlan() 輔助函數，將 DB 中舊的方案值（free/paid/custom）自動對應至新的四級方案（starter/standard/enterprise）。修復 SubscriptionBadge、FeatureGate、Pricing、Subscription、Admin 頁面及 server context 共 8 處讀取 plan 值的位置，防止未知值導致 undefined 存取錯誤。",
  },
  {
    version: "2.5.0",
    date: "2026-04-28",
    type: "minor",
    title: "四級訂閱方案重構 — Starter / Standard / Plus / Enterprise",
    description: "訂閱方案從 Free/Pro/Enterprise 三級改為 Starter/Standard/Plus/Enterprise 四級。Standard 含限制模板電子簽名（3 模板、30 次/月）、瀑布分析、投資人入口；Plus 解鎖無限模板、DCF 預測、反稀釋模型、台灣合規；Enterprise 含 SSO、API、專屬客戶經理。DB enum、plans.ts、Pricing 四欄、Compare Plans 五欄、FeatureGate、SubscriptionBadge、Admin 面板全站更新。",
  },
  {
    version: "2.4.0",
    date: "2026-04-28",
    type: "minor",
    title: "Landing Page Quick Start Guide — 新手引導流程",
    description: "重新設計空白狀態首頁：新增 5 步驟 Quick Start 指引（公司設定 → 投資人 → 募資輪次 → ESOP → Cap Table），附帶步驟編號、垂直連接線與 hover CTA。底部提示列含 Excel 匯入捷徑。下方保留 3×3 功能探索卡片。全站雙語 i18n。",
  },
  {
    version: "2.3.0",
    date: "2026-04-28",
    type: "minor",
    title: "Help & Support — FAQ + Feedback + 聯繫客服",
    description: "新增 /help 頁面含三個分頁：分類 FAQ（帳戶/訂閱/股權/技術/一般）含搜尋；意見回饋表單（feedback/feature request/bug）；聯繫客服表單（帳單/技術/客製化需求）含優先級。Header 新增問號 icon。Support tickets 存入 DB 並在 Admin Panel 新增工單管理頁。全站雙語 i18n（support namespace）。",
  },
  {
    version: "2.2.1",
    date: "2026-04-28",
    type: "patch",
    title: "Pricing / Compare Plans 頁面拆分",
    description: "將原本合併在 Pricing 頁的功能比較表拆為獨立 /compare-plans 頁面。Subscription 頁「比較方案」按鈕導向 /compare-plans，「變更方案」導向 /pricing。FeatureGate overlay 同步更新連結。",
  },
  {
    version: "2.2.0",
    date: "2026-04-28",
    type: "minor",
    title: "訂閱方案功能分級 — Feature Gating + 用量限制",
    description: "新增 shared/plans.ts 定義三級方案功能矩陣與用量上限。後端 planGuard middleware 攔截受限 API（14 個模組）；前端 FeatureGate 元件對 16 個頁面加上模糊升級覆蓋層。Pricing 頁新增完整功能比較表，Subscription 頁新增「比較方案」按鈕。Create 操作（股東、ESOP、公司、團隊邀請）加入用量檢查。",
  },
  {
    version: "2.1.0",
    date: "2026-04-28",
    type: "minor",
    title: "訂閱方案 — Badge + Pricing + Subscription 頁面",
    description: "右上角 Header 新增方案 Badge（Free/Pro/Enterprise），點擊進入訂閱管理頁。新增 Pricing 三欄比較頁（功能清單、升級 CTA）與 Subscription 管理頁（目前方案、使用量進度條、帳單區塊）。全站雙語 i18n（subscription namespace）。",
  },
  {
    version: "2.0.0",
    date: "2026-04-28",
    type: "major",
    title: "Layout 重構 — Content Header + Sidebar 精簡",
    description: "新增內容區頂部 Header Bar：Caploom logo、Admin Panel、語言切換、通知鈴鐺、登出。Sidebar Header 改為 CompanySwitcher（左）+ 收合按鈕（右）+ 使用者資訊（從 footer 上移）。Sidebar Footer 精簡為僅 VersionBadge。Mobile header 維持不變。",
  },
  {
    version: "1.23.2",
    date: "2026-04-28",
    type: "patch",
    title: "ClosedCompany 配置統一 + Rounds i18n 修復",
    description: "閉鎖性公司管理頁面改為與其他頁面一致的配置（p-8 max-w-6xl、inline icon、semantic token）。募資輪次頁面完成全欄位 i18n：新增 fundraising namespace hook、表格標頭、對話框、表單欄位、狀態 Badge、toast 訊息、刪除確認等全部改用 t() 呼叫。",
  },
  {
    version: "1.23.1",
    date: "2026-04-28",
    type: "patch",
    title: "ESOP 頁面 i18n 修復",
    description: "修復 ESOP 頁面 50+ 個硬編碼英文字串未連接翻譯系統的問題。KPI 卡片、表格標題、對話框、表單欄位、空白狀態、toast 訊息、行使流程等全部改用 t() 呼叫。新增 70 個 esop.* 翻譯鍵至 equity namespace。語言切換現在完整涵蓋 ESOP 所有 UI 元素。",
  },
  {
    version: "1.23.0",
    date: "2026-04-27",
    type: "minor",
    title: "i18n Phase 6 — 剩餘頁面 + 共用元件全站翻譯完成",
    description: "完成全站 i18n：Home Dashboard、EstimatedValuation、ShareClasses、Join、NotFound 五個頁面，以及 AllocationDialog、CompanySwitcher、NotificationBell、ChangelogDrawer、VestingTimeline 五個共用元件。新增 200+ 翻譯鍵至 pages / common namespace，涵蓋 KPI 卡片、圖表、漏斗、空白狀態、功能卡片、表單欄位等所有 UI 文字。全站零硬編碼字串。",
  },
  {
    version: "1.22.0",
    date: "2026-04-27",
    type: "minor",
    title: "i18n Phase 5 — Settings & Admin 全模組翻譯",
    description: "新增 settings / admin 兩個 namespace，完成 7 個頁面全欄位 i18n：AuditLog、Import、Team、Snapshots、AdminOverview、AdminCompanies、AdminActivity。稽核日誌、資料匯入、角色權限、團隊管理、快照操作、平台管理等 150+ 個翻譯鍵皆支援語言切換。",
  },
  {
    version: "1.21.0",
    date: "2026-04-27",
    type: "minor",
    title: "i18n Phase 4 — Equity, Fundraising & Analysis 全模組翻譯",
    description: "新增 equity / fundraising / analysis 三個 namespace，完成 12 個頁面全欄位 i18n：CapTable、ShareRegister、ESOP、ESign、FundingRounds、RoundDetail、Investors、Instruments、Waterfall、Valuation、Projections、AntiDilution。所有表單、表格、對話框、按鈕、模擬器皆支援語言切換。",
  },
  {
    version: "1.12.0",
    date: "2026-04-25",
    type: "minor",
    title: "Admin panel",
    description: "Platform admin backend — company management with subscription tiers (Free/Paid/Custom), audit log viewer, plan editor, suspend/reactivate, and admin activity tracking.",
  },
  {
    version: "1.11.0",
    date: "2026-04-25",
    type: "minor",
    title: "Navigation redesign",
    description: "Streamlined sidebar from 18 flat items to 6 collapsible groups — Dashboard, Equity, Fundraising, Analysis, Investor Portal, Settings — with auto-expanding active section.",
  },
  {
    version: "1.10.0",
    date: "2026-04-25",
    type: "minor",
    title: "Investor portal",
    description: "Dedicated read-only view for investors — see holdings by share class, ESOP vesting timeline, download share certificates, and track document signing status.",
  },
  {
    version: "1.9.0",
    date: "2026-04-25",
    type: "minor",
    title: "Share certificate PDF",
    description: "Generate formal share certificates from any issuance or ESOP exercise entry — includes company branding, certificate number, share details, and authorized signatory block.",
  },
  {
    version: "1.8.0",
    date: "2026-04-25",
    type: "minor",
    title: "Vesting schedule visualization",
    description: "Click any ESOP grant to expand an interactive vesting timeline — area chart with cliff/today markers, progress bar, and milestone cards.",
  },
  {
    version: "1.7.0",
    date: "2026-04-25",
    type: "minor",
    title: "ESOP exercise flow",
    description: "Exercise vested options into Common Stock with one click — atomically updates grant, writes to share register, and triggers cap table snapshot.",
  },
  {
    version: "1.6.0",
    date: "2026-04-25",
    type: "minor",
    title: "Investor portal",
    description: "投資人登入後可以查看持股、vesting 進度和文件簽署狀態。",
  },
  {
    version: "1.5.1",
    date: "2026-04-24",
    type: "patch",
    title: "Share class cleanup",
    description: "Removed ESOP from share class options — ESOP exercises into Common Stock. Corrected share class dropdown to show Common/Preferred only.",
  },
  {
    version: "1.5.0",
    date: "2026-04-24",
    type: "minor",
    title: "Data export",
    description: "Cap table PDF/Excel and share register Excel export with formatted workbooks, frozen headers, and dynamic share class names.",
  },
  {
    version: "1.4.0",
    date: "2026-04-24",
    type: "minor",
    title: "Share class management",
    description: "Define equity classes with preferred terms — liquidation multiple, participation type, anti-dilution, dividends, voting rights, and conversion ratio.",
  },
  {
    version: "1.3.0",
    date: "2026-04-24",
    type: "minor",
    title: "eSignature template library",
    description: "Two-layer template system: platform-wide templates for all companies and company-scoped templates for custom contracts.",
  },
  {
    version: "1.2.0",
    date: "2026-04-24",
    type: "minor",
    title: "DocuSeal eSignature",
    description: "Send equity documents for signing via DocuSeal — create templates from PDF/DOCX, track signing status, and receive webhook notifications.",
  },
  {
    version: "1.1.1",
    date: "2026-04-23",
    type: "patch",
    title: "Mobile responsive layout",
    description: "Bottom navigation bar, scrollable tables, and responsive grid layouts for mobile devices.",
  },
  {
    version: "1.1.0",
    date: "2026-04-22",
    type: "minor",
    title: "Instruments — SAFE & Convertible Notes",
    description: "Track SAFEs and convertible notes with conversion modeling, interest accrual, and batch conversion to equity.",
  },
  {
    version: "1.0.0",
    date: "2026-04-20",
    type: "major",
    title: "Caploom v1 launch",
    description: "Cap table, share register, funding rounds, investor pipeline, ESOP management, waterfall analysis, financial projections, and audit logging.",
  },
];

/** Current version — always the first entry. */
export const CURRENT_VERSION = CHANGELOG[0].version;
